site_name: echemdb.org
site_dir: generated/website
docs_dir: pages
theme:
  name: material
  palette:
    scheme: default
    primary: black
    accent: lime
  features:
  - navigation.tabs
  - navigation.indexes
  - navigation.tabs.sticky
  - toc.follow

extra_css:
  - stylesheets/extra.css
  - stylesheets/katex.css
  - https://cdn.jsdelivr.net/npm/katex@0.16/dist/katex.min.css

plugins:
  - search
  - macros
  - gen-files:
      scripts:
      - website/generator/__main__.py
  - section-index
  - literate-nav:
      nav_file: NAVIGATION.md
  - mkdocs-simple-hooks:
      enabled: !ENV [ENABLE_MKDOCS_COPY_DATA, True]
      hooks:
        on_post_build: "website.hooks:copy_data"

markdown_extensions:
  - extra
  - admonition
  - codehilite
  - smarty
  - meta
  - def_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - markdown_include.include:
      base_path: pages
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/config.js
  - https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js
  - javascripts/tables.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://cdn.jsdelivr.net/npm/d3@7
  - javascripts/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.16/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16/dist/contrib/mhchem.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16/dist/contrib/auto-render.min.js
